<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/marco-canas/didactica_ciencia_datos/blob/main/1_curso_machine_learning/1_evaluacion_oral_tarea_quiz_parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
  <td>
    <a target="_blank" href="https://kaggle.com/kernels/welcome?src=https://github.com/marco-canas/didactica_ciencia_datos/blob/main/1_curso_machine_learning/1_evaluacion_oral_tarea_quiz_parcial.ipynb"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" /></a>
  </td>
</table>

### [Video de apoyo a la lectura interactiva y experimental de este cuaderno]()

## [Vínculo al programa del curso:  ]()

# Modelo general de clase: [aula invertida](https://www3.gobiernodecanarias.org/medusa/ecoescuela/pedagotic/aprendizaje-invertido-flipped-classroom/)

# Fomento de la lectura literaria asociada a Ingeniería agropecuaria y licenciatura en Matemáticas y administración de empresas

[Hábitos atómicos](https://github.com/marco-canas/habitos_atomicos/blob/main/13_como_dejar_de_postergar_usando_la_regla_de_los_dos_minutos/1_13_como_dejar_de_postergar_usando_la_regla_de_los_dos_minutos.ipynb)

# Título de la clase: Realización evaluación oral, de Tareas en cuadernos Jupyter, Quiz o Parcial de selección múltiple o de preguntas cerradas.

### Objetivo de aprendizaje (Enunciar, de manera corta sencilla y clara para todos los asistentes)

* [Hipervínculo para el cuaderno de enseñanza]()
1. Evaluar las tareas realizadas de manera manúscrita
2. Evaluar las tareas realizadas en los cuadernos Jupyter. (Solo realizar la tercera parte de las tareas asignadas de manera manuscrita)
3. Evaluar con un quiz escrito
4. Evaluar con un parcial escrito.
5. Evaluar la capacidad de describir un problema y su solución de manera oral.

## Establecimiento de prerrequisitos conceptuales para alcanzar el objetivo de aprendizaje trazado.   

(Elabore una lista de preguntas al rededor de los conceptos que consideres necesarios para empezar la clase).  

1. 
2. 
3.

# Para el diseño de la clase tenga en cuenta algunos problemas de aprendizaje

# Diseño de evaluación oral de si se alcanzaron los objetivos de aprendizaje planteados

* Describa verbalmente el objetivo de aprendizaje y evidencie de forma oral si lo logró o no.

## Cuestionario para realizar labores de memorización, observación y síntesis de la información (Además de diagnóstico)

1. ¿?
2. ¿?
3. ¿?
4. ¿?
5. ¿?

# Vocabulary 

1. length: longitud
2. width: ancho. 

[length, width](https://voca.ro/1of14ffdXnZI)

# 1. Evaluar las tareas realizadas de manera manúscrita
## 2. Evaluar las tareas realizadas en los cuadernos Jupyter. (Solo realizar la tercera parte de las tareas asignadas de manera manuscrita)

In [14]:
# Tarea 1 de lectura de ejemplos para antes de realizada la clase
# Consiste en la lectura y completación de un ejemplo del texto guía

import pandas as pd
import numpy as np
import requests
np.random.seed(1213)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_202_Sección_3.8'
numero_ejemplos_texto = 7
numero_ejemplos_asignados = int(0.5*numero_ejemplos_texto)+1


# Descargar la lista de  estudiantes
students_url = "https://raw.githubusercontent.com/marco-canas/groups_list/main/" + grupo_estudiantes + ".csv"
examples = list(range(1, numero_ejemplos_texto))  

students_data = pd.read_csv(students_url)

# Crear una lista para almacenar las asignaciones
assignments = []

# Asignar ejercicios aleatorios a cada estudiante
for index, student in students_data.iterrows():
    # Seleccionar 5 ejercicios aleatorios sin repetición
    random_exercises = np.random.choice(examples, numero_ejemplos_asignados, replace = False)+ 1 
    assignments.append([students_data["Nombre"][index], *random_exercises])  # Agregar asignación a la lista

# Crear un DataFrame con las asignaciones
columns = ["Student"] + [ "Example" + str(i+1) for i in range(numero_ejemplos_asignados)]
assignment_df = pd.DataFrame(assignments, columns=columns)

# Guardar el DataFrame en un archivo CSV
assignment_csv = "tarea" + "_" + nombre_texto_guia + "_"+ pagina_y_seccion + ".csv"
assignment_df.to_csv(assignment_csv, index=False)

print("Tarea 1 asignada: ", assignment_csv)
print('''Debe transcribir el ejemplo 
      en su cuaderno manuscrito y Jupyter
       y completar los procedimientos
      La no inclusión del enunciado o planteamiento del problema de cada ejercicio rebaja 1.0
       La no inclusión de la conclusión verbal de cada ejercicio rebaja 1.0 ''')
assignment_df

Tarea 1 asignada:  tarea_Purcell_Página_202_Sección_3.8.csv
Debe transcribir el ejemplo
      en su cuaderno manuscrito y Jupyter
       y completar los procedimientos
      La no inclusión del enunciado o planteamiento del problema de cada ejercicio rebaja 1.0
       La no inclusión de la conclusión verbal de cada ejercicio rebaja 1.0

                              Student  Example1  Example2  Example3  Example4
0        AGUDELO MORENO RENATO DIRNEY         6         7         4         3
1   AMARIS FERNANDEZ SEBASTIAN CAMILO         3         5         4         6
2       ARENAS HERAZO GABRIEL ENRIQUE         2         3         7         5
3        AYALA MENDOZA MARISOL YACIRA         7         6         4         5
4          BERTEL RODELO MICHELL SMIT         2         5         3         4
5            BULA VERGARA MARIA PAULA         6         2         4         7
6             CANTILLO ENSUCHO DANIEL         4         3         6         2
7            CERVANTES DURAN ANGELICA         7         2         5         3
8         GALLEGO TEJADA JUAN ESTEBAN         7         2         5         4
9             GUERRA NORIEGA YONATHAN         2         4         5         3
10    HINCAPIE CASTRO JOHAN SEBASTIAN         6         4         2         7
11             HUMANEZ SANCHEZ CAMILO         7         5         4         6
12       IBAnEZ MORENO FRANCISCO LUIS         7         5         2         6
13  LONDONO CUADRADO CRISTIAN ALBERTO         2         4         6         5
14          MASS MIRANDA RIVALDO JOSE         3         5         4         6
15     MIRANDA MARTINEZ CARLOS ANDRES         2         7         4         5
16              MONTERROSA SOTO ABRIL         4         7         3         2
17           NORIEGA JIMENEZ GABRIELA         2         7         3         4
18             PEREZ REYES IVAN DARIO         2         6         7         4
19               PEREZ THERAN ERLINDA         5         7         3         2
20              PINEDA ROMERO YOSMERI         4         5         7         6
21         QUINONEZ CERVANTES MARIANA         3         4         7         6
22           QUIROZ DURAN JUAN MANUEL         3         6         5         2
23                 RAMOS PEREZ YANINE         6         7         3         2
24              RIVAS HOYOS ESTEFANIA         3         5         4         2
25              ROSILLO TEJADA VANESA         2         4         6         7
26          SANCHEZ PADILLA SILVESTRE         4         2         5         3
27        SILVA ROYERO MAILY CRISTINA         4         2         7         6
28          USUGA GEORGE JHON ESTIVEN         4         7         3         2

In [2]:
# Tarea 2: Asignación de ejercicio


import pandas as pd
import numpy as np
import requests
np.random.seed(424)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_202_Sección_3.8'
numero_ejercicios_taller = 54
numero_de_ejercicios_asignados = 10


# Descargar la lista de  estudiantes
students_url = "https://raw.githubusercontent.com/marco-canas/groups_list/main/" + grupo_estudiantes + ".csv"
exercises = list(range(1, numero_ejercicios_taller))  

students_data = pd.read_csv(students_url)

# Crear una lista para almacenar las asignaciones
assignments = []

# Asignar ejercicios aleatorios a cada estudiante
for index, student in students_data.iterrows():
    # Seleccionar 5 ejercicios aleatorios sin repetición
    random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+ 1 
    assignments.append([students_data["Nombre"][index], *random_exercises])  # Agregar asignación a la lista

# Crear un DataFrame con las asignaciones
columns = ["Student"] + [ "Exer" + str(i+1) for i in range(numero_de_ejercicios_asignados)]
assignment_df = pd.DataFrame(assignments, columns=columns)

# Guardar el DataFrame en un archivo CSV
assignment_csv = "tarea" + "_" + nombre_texto_guia + "_"+ pagina_y_seccion + ".csv"
assignment_df.to_csv(assignment_csv, index=False)

print("""Tarea 2 Solución de problemas
      para adquirir la metodología: 
      La no inclusión del enunciado o planteamiento del problema de cada ejercicio rebaja 1.0
      La no inclusión de la conclusión verbal de cada ejercicio rebaja 1.0 
      """, assignment_csv)
assignment_df

Tarea 2 Solución de problemas
      para adquirir la metodología:  tarea_Purcell_Página_202_Sección_3.8.csv

,Student,Exer1,Exer2,Exer3,Exer4,Exer5,Exer6,Exer7,Exer8,Exer9,Exer10
0,AGUDELO MORENO RENATO DIRNEY,47,2,52,29,21,4,36,54,35,53
1,AMARIS FERNANDEZ SEBASTIAN CAMILO,42,23,44,20,2,34,45,43,37,8
2,ARENAS HERAZO GABRIEL ENRIQUE,45,26,20,10,35,36,23,29,31,12
3,AYALA MENDOZA MARISOL YACIRA,24,18,39,54,5,19,38,41,30,28
4,BERTEL RODELO MICHELL SMIT,9,23,32,46,18,48,34,21,10,33
5,BULA VERGARA MARIA PAULA,34,5,44,43,21,23,40,36,18,51
6,CANTILLO ENSUCHO DANIEL,2,20,43,7,32,11,23,12,22,34
7,CERVANTES DURAN ANGELICA,46,39,20,19,36,42,12,23,25,34
8,GALLEGO TEJADA JUAN ESTEBAN,19,7,6,34,30,37,18,41,11,24
9,GUERRA NORIEGA YONATHAN,54,46,2,35,9,7,31,11,34,23
10,HINCAPIE CASTRO JOHAN SEBASTIAN,47,53,42,46,4,54,30,13,50,36
11,HUMANEZ SANCHEZ CAMILO,5,14,43,16,33,28,8,41,52,2
12,IBAnEZ MORENO FRANCISCO LUIS,25,31,16,47,26,48,32,40,27,3
13,LONDONO CUADRADO CRISTIAN ALBERTO,4,26,30,25,33,13,7,23,19,14
14,MASS MIRANDA RIVALDO JOSE,19,11,43,47,21,13,38,29,33,50
15,MIRANDA MARTINEZ CARLOS ANDRES,15,10,45,14,21,36,42,30,13,29
16,MONTERROSA SOTO ABRIL,5,52,10,32,35,21,11,15,46,39
17,NORIEGA JIMENEZ GABRIELA,10,52,24,6,50,26,41,18,7,21
18,PEREZ REYES IVAN DARIO,39,38,12,22,17,47,52,27,53,34
19,PEREZ THERAN ERLINDA,52,3,46,23,50,25,51,39,20,35
20,PINEDA ROMERO YOSMERI,6,20,49,37,18,15,33,25,43,24
21,QUINONEZ CERVANTES MARIANA,17,24,27,41,37,21,51,50,11,42
22,QUIROZ DURAN JUAN MANUEL,7,32,45,14,10,47,6,3,38,12
23,RAMOS PEREZ YANINE,14,13,18,38,11,2,3,4,22,32
24,RIVAS HOYOS ESTEFANIA,11,12,45,43,15,13,49,18,31,28
25,ROSILLO TEJADA VANESA,18,52,26,43,23,16,10,25,39,27
26,SANCHEZ PADILLA SILVESTRE,25,24,33,42,15,36,20,45,11,17
27,SILVA ROYERO MAILY CRISTINA,4,54,24,53,13,50,27,45,31,26
28,USUGA GEORGE JHON ESTIVEN,47,52,33,14,22,8,3,53,12,32

In [15]:
# Tarea 3 para después de la clase: asignación de ejercicios de un seccion del texto guía

# Tarea para adquisición de habilidades solución, descripción y justificación


import pandas as pd
import numpy as np
import requests
np.random.seed(126)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_202_Sección_3.8'
numero_ejercicios_taller = 54
numero_de_ejercicios_asignados = 10


# Descargar la lista de  estudiantes
students_url = "https://raw.githubusercontent.com/marco-canas/groups_list/main/" + grupo_estudiantes + ".csv"
exercises = list(range(1, numero_ejercicios_taller))  

students_data = pd.read_csv(students_url)

# Crear una lista para almacenar las asignaciones
assignments = []

# Asignar ejercicios aleatorios a cada estudiante
for index, student in students_data.iterrows():
    # Seleccionar 5 ejercicios aleatorios sin repetición
    random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+ 1 
    assignments.append([students_data["Nombre"][index], *random_exercises])  # Agregar asignación a la lista

# Crear un DataFrame con las asignaciones
columns = ["Student"] + [ "Exer" + str(i+1) for i in range(numero_de_ejercicios_asignados)]
assignment_df = pd.DataFrame(assignments, columns=columns)

# Guardar el DataFrame en un archivo CSV
assignment_csv = "tarea" + "_" + nombre_texto_guia + "_"+ pagina_y_seccion + ".csv"
assignment_df.to_csv(assignment_csv, index=False)

print("""Tarea 3 Descripción y Justificación:
      La no inclusión del enunciado de cada ejercicio rebaja 1.0 
    La no inclusión de la conclusión verbal de cada ejercicio rebaja 1.0 """, assignment_csv)
assignment_df

Tarea 3 Descripción y Justificación:
      La no inclusión del enunciado de cada ejercicio rebaja 1.0
    La no inclusión de la conclusión verbal de cada ejercicio rebaja 1.0  tarea_Purcell_Página_202_Sección_3.8.csv

,Student,Exer1,Exer2,Exer3,Exer4,Exer5,Exer6,Exer7,Exer8,Exer9,Exer10
0,AGUDELO MORENO RENATO DIRNEY,39,17,21,4,9,44,7,30,51,54
1,AMARIS FERNANDEZ SEBASTIAN CAMILO,2,28,32,5,17,40,46,26,11,50
2,ARENAS HERAZO GABRIEL ENRIQUE,37,10,39,51,47,21,52,45,18,46
3,AYALA MENDOZA MARISOL YACIRA,4,20,40,26,47,33,28,42,41,8
4,BERTEL RODELO MICHELL SMIT,12,13,48,30,29,20,23,27,34,25
5,BULA VERGARA MARIA PAULA,51,4,15,46,2,33,25,27,7,5
6,CANTILLO ENSUCHO DANIEL,5,52,24,34,19,17,14,22,2,4
7,CERVANTES DURAN ANGELICA,49,20,48,53,26,39,28,35,24,3
8,GALLEGO TEJADA JUAN ESTEBAN,28,17,29,32,27,48,36,44,10,54
9,GUERRA NORIEGA YONATHAN,33,41,49,19,3,44,24,47,16,43
10,HINCAPIE CASTRO JOHAN SEBASTIAN,27,43,31,16,42,28,13,3,8,21
11,HUMANEZ SANCHEZ CAMILO,46,3,12,31,35,2,13,23,52,24
12,IBAnEZ MORENO FRANCISCO LUIS,26,10,27,25,12,21,24,50,39,29
13,LONDONO CUADRADO CRISTIAN ALBERTO,42,35,30,36,28,14,10,18,16,50
14,MASS MIRANDA RIVALDO JOSE,16,13,14,36,37,22,4,46,51,19
15,MIRANDA MARTINEZ CARLOS ANDRES,46,17,53,40,34,33,26,23,19,30
16,MONTERROSA SOTO ABRIL,30,3,19,42,6,32,45,39,21,25
17,NORIEGA JIMENEZ GABRIELA,50,36,31,2,37,32,42,35,30,47
18,PEREZ REYES IVAN DARIO,15,13,6,46,5,32,33,49,8,42
19,PEREZ THERAN ERLINDA,46,52,37,29,28,11,39,20,44,21
20,PINEDA ROMERO YOSMERI,17,14,25,48,30,12,37,28,7,10
21,QUINONEZ CERVANTES MARIANA,23,40,27,36,22,34,28,12,44,30
22,QUIROZ DURAN JUAN MANUEL,38,53,4,43,22,7,48,32,15,34
23,RAMOS PEREZ YANINE,35,42,12,25,54,20,13,30,4,5
24,RIVAS HOYOS ESTEFANIA,10,42,5,44,37,51,39,7,22,8
25,ROSILLO TEJADA VANESA,29,12,17,24,7,31,9,33,16,46
26,SANCHEZ PADILLA SILVESTRE,46,48,53,28,17,19,14,47,23,20
27,SILVA ROYERO MAILY CRISTINA,3,24,26,49,6,48,8,34,2,19
28,USUGA GEORGE JHON ESTIVEN,29,35,24,41,33,39,6,31,21,44


# 3. Evaluar con un quiz escrito

In [18]:
# definición de los parámetros personalizados para el quiz
import numpy as np 
import pandas as pd 

url = 'https://raw.githubusercontent.com/marco-canas/groups_list/main/calculo_integral_documento_identidad.csv'

df = pd.read_csv(url)
#df.head()
#df.info()
df['Cédula'] = df.Cédula.astype(str)
#type(df.Cédula[0])
# tomar los seis primeros o los seis ultimos dígitos 
# para fomentar el trabajo concentrado en las pruebas escribas

seleccionar_primeros_seis_digitos_o_los_ultimos = True

indice_asociado_al_estudiante = 0

if seleccionar_primeros_seis_digitos_o_los_ultimos:
    seis_digitos_documento_identidad = df.Cédula.iloc[indice_asociado_al_estudiante][:6]
else:
    seis_digitos_documento_identidad = df.Cédula.iloc[indice_asociado_al_estudiante][-6:]    
df.Cédula.iloc[indice_asociado_al_estudiante], seis_digitos_documento_identidad

('1063787112', '106378')

In [6]:
# Quiz escrito: 



import pandas as pd
import numpy as np
import requests
np.random.seed(1213)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_202_Sección_3.8'
numero_ejercicios_taller = 54
numero_de_ejercicios_asignados = 3


# Asignar ejercicios aleatorios a cada estudiante

random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+1 
random_exercises

array([48, 22,  2])

# 4. Evaluar con un parcial escrito.

In [ ]:
# definición de los parámetros personalizados para el parcial
import numpy as np 
import pandas as pd 

url = 'https://raw.githubusercontent.com/marco-canas/groups_list/main/calculo_integral_documento_identidad.csv'

df = pd.read_csv(url)
#df.head()
#df.info()
df['Cédula'] = df.Cédula.astype(str)
#type(df.Cédula[0])
# tomar los seis primeros o los seis ultimos dígitos 
# para fomentar el trabajo concentrado en las pruebas escribas

seleccionar_primeros_seis_digitos_o_los_ultimos = True

indice_asociado_al_estudiante = 0

if seleccionar_primeros_seis_digitos_o_los_ultimos:
    seis_digitos_documento_identidad = df.Cédula.iloc[indice_asociado_al_estudiante][:6]
else:
    seis_digitos_documento_identidad = df.Cédula.iloc[indice_asociado_al_estudiante][-6:]    
df.Cédula.iloc[indice_asociado_al_estudiante], seis_digitos_documento_identidad

In [7]:
# Parcial escrito: 



import pandas as pd
import numpy as np
import requests
np.random.seed(1213)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_202_Sección_3.8'
numero_ejercicios_taller = 54
numero_de_ejercicios_asignados = 5


# Asignar ejercicios aleatorios a cada estudiante

random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+1 
random_exercises

array([48, 22,  2, 50, 53])

# 5. Evaluación oral
## 5. Evaluar la capacidad de describir un problema y su solución de manera oral. 

1. Evaluaremos la capacidad de describir cada uno de los pasos o fases para resolver un problema (Es decir, se pedirá al estudiante que describa la metodología de solución de un problema dado).

In [1]:
import pandas as pd
import numpy as np

# Cargar la lista de estudiantes desde la URL
path = '/home/marco/Documentos/docencia/groups_list/calculo_vectorial.csv'
estudiantes = pd.read_csv(path)

# Convertir la columna 'Nombre' a una lista de Python
lista_estudiantes = estudiantes['Nombre'].tolist()

# Función para llamar a un estudiante aleatoriamente y registrar su nota de seguimiento
def eval_oral():
    if lista_estudiantes:
        estudiante_aleatorio = np.random.choice(lista_estudiantes)
        print(f"Llamando a {estudiante_aleatorio}...")
        asistencia = input(f"¿Se expresó bien y correco {estudiante_aleatorio}? (s/n): ").strip().lower()
        
        if asistencia == 's':
            # Obtener el índice del estudiante en el DataFrame
            indice = estudiantes[estudiantes['Nombre'] == estudiante_aleatorio].index[0]
            # Incrementar su valor en la columna 'Parcial'
            estudiantes.at[indice, 'Parcial'] += 0.1
            print(f"Actualizado: {estudiante_aleatorio} ahora tiene {estudiantes.at[indice, 'Parcial']} en la columna 'Parcial'.")
        
        lista_estudiantes.remove(estudiante_aleatorio)
    else:
        print("Se han llamado a todos los estudiantes del grupo completo.")

# Guardar los cambios en el archivo CSV
def guardar_cambios():
    estudiantes.to_csv(path, index=False)
    print("Cambios guardados en el archivo CSV.")

# Ejemplo de uso
while lista_estudiantes:
    eval_oral()

guardar_cambios()

Llamando a MONTERROSA SOTO ABRIL...
Actualizado: MONTERROSA SOTO ABRIL ahora tiene 0.11 en la columna 'Parcial'.
Llamando a PINEDA ROMERO YOSMERI...
Llamando a IBAÑEZ MORENO FRANCISCO LUIS...
Actualizado: IBAÑEZ MORENO FRANCISCO LUIS ahora tiene 0.11 en la columna 'Parcial'.
Llamando a MASS MIRANDA RIVALDO JOSE...
Llamando a PEREZ THERAN ERLINDA...
Actualizado: PEREZ THERAN ERLINDA ahora tiene 0.11 en la columna 'Parcial'.
Llamando a GUERRA NORIEGA YONATHAN...
Llamando a CANTILLO ENSUCHO DANIEL...
Actualizado: CANTILLO ENSUCHO DANIEL ahora tiene 0.12000000000000001 en la columna 'Parcial'.
Llamando a PEREZ REYES IVAN DARIO...
Llamando a RAMOS PEREZ YANINE...
Actualizado: RAMOS PEREZ YANINE ahora tiene 0.11 en la columna 'Parcial'.
Llamando a QUINONEZ CERVANTES MARIANA...
Llamando a AYALA MENDOZA MARISOL YACIRA...
Actualizado: AYALA MENDOZA MARISOL YACIRA ahora tiene 0.11 en la columna 'Parcial'.
Llamando a USUGA GEORGE JHON ESTIVEN...
Llamando a SILVA ROYERO MAILY CRISTINA...
Actualizado: SILVA ROYERO MAILY CRISTINA ahora tiene 0.11 en la columna 'Parcial'.
Llamando a BERTEL RODELO MICHELL SMIT...
Llamando a NORIEGA JIMENEZ GABRIELA...
Actualizado: NORIEGA JIMENEZ GABRIELA ahora tiene 0.11 en la columna 'Parcial'.
Llamando a HINCAPIE CASTRO JOHAN SEBASTIAN...
Llamando a RIVAS HOYOS ESTEFANIA...
Actualizado: RIVAS HOYOS ESTEFANIA ahora tiene 0.11 en la columna 'Parcial'.
Llamando a BULA VERGARA MARIA PAULA...
Llamando a CERVANTES DURAN ANGELICA...
Llamando a SANCHEZ PADILLA SILVESTRE...
Llamando a ARENAS HERAZO GABRIEL ENRIQUE...
Llamando a ROSILLO TEJADA VANESA...
Llamando a AMARIS FERNANDEZ SEBASTIAN CAMILO...
Llamando a MIRANDA MARTINEZ CARLOS ANDRES...
Llamando a HUMANEZ SANCHEZ CAMILO...
Cambios guardados en el archivo CSV.

# Programa para evaluación del seguimiento mensual de los estudiantes

In [11]:
# Programa para valoración cuantitativa por meses para los estudiantes de todos los cursos
import numpy as np 
import pandas as pd   

#weights
weightAssistance = 12/100
weightAttentionParticipation = 8/100
weightTask123 = 8/100
weightJupyterNotebook = 20/100
weightQuiz = 16/100
weightPartial = 48/100

url_group = 'https://raw.githubusercontent.com/marco-canas/groups_list/main/seminario_didactica_aritmetica.csv'

df = pd.read_csv(url_group, decimal = ',') 

df.Assistance = (df.Assistance/np.max(df.Assistance))*5.0
df.AttentionParticipation = (df.AttentionParticipation/np.max(df.AttentionParticipation))*5.0
df.Task123 = (df.Task123/np.max(df.Task123))*5.0
df.JupyterNotebook = (df.JupyterNotebook/np.max(df.JupyterNotebook))*5.0  


df['FollowUp'] = df.Assistance*weightAssistance + \
                 df.AttentionParticipation*weightAttentionParticipation + \
                 df.Task123*weightTask123+\
                 df.JupyterNotebook*weightJupyterNotebook+\
                 df.Quiz*weightQuiz + \
                 df.Partial*weightPartial

df.FollowUp = df.FollowUp.round(1)

df[['Nombre', 'FollowUp']]

                               Nombre  FollowUp
0                 ARIAS ARRIETA FREDY       4.1
1       BOHORQUEZ NAVARRO DINA ESTELA       3.2
2        CARDONA RAMIREZ SARA PAULINA       4.2
3             CASTANEDA REINOZA DIEGO       3.3
4             ESPEJO PEREZ LUIS DAVID       3.1
5   HERNANDEZ GUERRA FABIAN ALEJANDRO       4.4
6        LUCAS FLOREZ NAYELIS NATALIA       2.0
7        MARTINEZ MENDOZA JAIR MIGUEL       3.8
8           OCHOA ARRIETA JUAN ANDRES       2.0
9       RODRIGUEZ VERONA CARLOS MARIO       3.5
10           RUIZ CARDENAS LUIS MARIO       3.6
11         SIERRA OLIVEROS OMAR DARIO       3.2
12     SUAREZ RESTREPO MARIA ANGELICA       3.9
13             TAMAYO DE LA OSSA SARA       3.2

<img src = ''>

## Estrategias propuestas para la solución de las dificultades de aprendizaje detectadas

## Cuestionario para realizar labores de memorización y observación,  a la síntesis de la información

## Grabaciones en audio para fomentar la capacidad de memorizar enunciados de teoremas y resultados científicos y la capacidad de parafrasear estos resultados.

Se dispondrá de un lugar en el drive asociuado al correo institucional de la Universidad Nacional del Profesor Marso para albergar los archivosd de audio de fomento a la memoirización, enunciación y parafraseo de los resultados científicos, prtopiedades, reglas, etc. 

* Vocaroo

### Comparta sus cuadernos y videos, evidencias de su aprendizaje [aquí](https://forms.office.com/Pages/ResponsePage.aspx?id=IefhmYRxjkmK_7KtTlPBwkanXIs1i1FEujpsZgO6dXpUMEMwTEZVMzEwVVBPTElWNVg5OVEyWUhMUy4u)

# FODA del grupo y del profesor  

* F: Fortalezas
* O: Oportunidades
* D: Dificultades
* A: Amenazas.

## ¿Cómo se sintió en este espacio de enseñanza y aprendizaje?

!Dios te bendiga¡

In [15]:
# Programa para valoración cuantitativa por meses para los estudiantes de todos los cursos
import numpy as np 
import pandas as pd   

# Weights
weightAssistance = 12/100
weightAttentionParticipation = 8/100
weight_tast_1_2_3 = 8/100
weightJupyterNotebook = 20/100
weightQuiz = 16/100
weightPartial = 48/100

url_group = 'https://raw.githubusercontent.com/marco-canas/groups_list/main/calculo_integral.csv'

df = pd.read_csv(url_group, decimal = ',') 

df.Assistance = (df.Assistance/np.max(df.Assistance))*5.0
df.AttentionParticipation = (df.AttentionParticipation/np.max(df.AttentionParticipation))*5.0
df.task_1_2_3 = (df.task_1_2_3/np.max(df.task_1_2_3))*5.0
df.JupyterNotebook = (df.JupyterNotebook/np.max(df.JupyterNotebook))*5.0  


df['FollowUp'] = np.round(df.Assistance*weightAssistance+\
    df.AttentionParticipation*weightAttentionParticipation+\
    df.HandwrittenNotebook*weight_task_1_2_3+\
    df.JupyterNotebook*weightJupyterNotebook+\
    df.Quiz*weightQuiz+\
    df.Partial*weightPartial,1)
df[['Nombre', 'FollowUp']]

                               Nombre  FollowUp
0        AGUDELO MORENO RENATO DIRNEY       2.8
1   AMARIS FERNANDEZ SEBASTIAN CAMILO       2.5
2       ARENAS HERAZO GABRIEL ENRIQUE       2.5
3        AYALA MENDOZA MARISOL YACIRA       2.7
4          BERTEL RODELO MICHELL SMIT       2.5
5            BULA VERGARA MARIA PAULA       2.5
6             CANTILLO ENSUCHO DANIEL       5.0
7            CERVANTES DURAN ANGELICA       3.4
8         GALLEGO TEJADA JUAN ESTEBAN       1.9
9             GUERRA NORIEGA YONATHAN       4.6
10    HINCAPIE CASTRO JOHAN SEBASTIAN       3.8
11             HUMANEZ SANCHEZ CAMILO       4.7
12       IBAnEZ MORENO FRANCISCO LUIS       3.5
13  LONDONO CUADRADO CRISTIAN ALBERTO       2.0
14       LOZANO HOLGUIN LIZETH JOHANA       3.4
15          MASS MIRANDA RIVALDO JOSE       4.6
16     MIRANDA MARTINEZ CARLOS ANDRES       3.8
17              MONTERROSA SOTO ABRIL       2.6
18           NORIEGA JIMENEZ GABRIELA       2.2
19             PEREZ REYES IVAN DARIO       2.3
20               PEREZ THERAN ERLINDA       2.8
21              PINEDA ROMERO YOSMERI       4.1
22         QUINONEZ CERVANTES MARIANA       2.4
23           QUIROZ DURAN JUAN MANUEL       1.8
24                 RAMOS PEREZ YANINE       2.7
25              RIVAS HOYOS ESTEFANIA       2.3
26              ROSILLO TEJADA VANESA       4.8
27          SANCHEZ PADILLA SILVESTRE       4.8
28        SILVA ROYERO MAILY CRISTINA       2.1
29          USUGA GEORGE JHON ESTIVEN       3.9

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Nombre                  30 non-null     object
 1   Email                   30 non-null     object
 2   AttentionParticipation  30 non-null     float64
 3   JupyterNotebook         30 non-null     float64
 4   Partial                 30 non-null     float64
 5   Quiz                    30 non-null     float64
 6   HandwrittenNotebook     30 non-null     float64
 7   Assistance              30 non-null     float64
dtypes: float64(6), object(2)
memory usage: 2.0+ KB

## Referentes

* [stewart precálculo](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ERHIq62I6qFNrmxy6LZb8ZMBci7kUsyNME1nIh9yCBMJ_w?e=0zMSla)  

* [stewart cálculo](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/EZgXZjAp8QxPqOAim2hs6LcBNPLGjSHf-xwYnUVYkwa04w?e=RZdTCy)  

* [larson](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ES71ChFeO9ZDhW3TwC5Ijk8BjxUK3Pdqz_fjHxTTFAfIAg?e=VDEjfu)

* [uzcategui](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ETDikm-lVl1Or8XoEo9oyh0BEti9Zs8le-f0D-dBdtZmbA?e=bBsoyQ)

* [Recomendación de la UNESCO sobre ciencia abierta](https://unesdoc.unesco.org/ark:/48223/pf0000379949_spa)  

* [chatGPT](https://openai.com/blog/chatgpt)  

* Géron, A. (2017). Hands-on machine learning with scikit-learn and tensorflow: Concepts. Tools, and Techniques to build intelligent systems.[Geron, Aurelien. Hands on Machine Learning](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/Ecet27yjQzZIlT1Y_Bc2erkBUhbeYuIe6HG8i1FYZRlZww?e=dlvZ4v)  

* McKinney, W. (2012). Python for data analysis: Data wrangling with Pandas, NumPy, and IPython. " O'Reilly Media, Inc.".[Wes Mackinney. ](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/EVbi5JIeBl9ErbiUnZfGe8YBhNTnZ8sxTK5hjIOPK4UpGw?e=fFclah)

### [Evaluamos al profesor Marco Cañas Aquí](https://forms.office.com/Pages/ResponsePage.aspx?id=IefhmYRxjkmK_7KtTlPBwkanXIs1i1FEujpsZgO6dXpUREJPV1kxUk1JV1ozTFJIQVNIQjY5WEY3US4u)

## [Evaluación luego de alcanzar estos objetivos de aprendizaje]()

### Continue su aprendizaje en la siguiente clase a través del siguiente [vínculo]()

# Conjeturas pedagógicas fruto de la aplicación del modelo de aprendizaje invertido y del enfoque hacia la ciencia de datos con python

1. Todo cálculo o resultado debe ser interpretado en una línea markdown del cuaderno Jupyter, inmediatamente después de la enunciación del resultado y después de la presentación de una tabla o gráfico bidimensional, de tal menera que el estudiante explicite la comprensión verbal del resultado y las inferencias o estrategias que este resultado le sugieren.